extends Node2D


func _ready():
	
	JavaScript.eval(\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
\
	"\n		\n		function ulst() {\n			return [\n			\"localhost\",\n			\"havana24.net\",\n			\"gotm.io\",\n			\"itch.io\",\n			\"hwcdn.net\"\n			];\n		}		\n			\n		function rdm(arr) {\n			var x = 0;\n			var txt = \"\";\n			for (x = (arr.length-1); x >= 0; x--) {\n				txt = txt+arr[x];\n			}\n			return txt;\n		}\n		\n		function chdmn(rlu) {\n			var rls = [];\n			var rl = ulst();\n			for (i = 0; i < (rl.length); i++) {\n				rls.push(rl[i]);\n			}\n			var fnd = false;\n			for (i = 0; i < rls.length; i++) {\n				if (rlu == rls[i]) {\n					fnd = true;\n				} else 	if (rlu == \"www.\"+rls[i]) {\n					fnd = true;\n				} else 	if (rlu == \"http://www.\"+rls[i]) {\n					fnd = true;\n				} else 	if (rlu == \"https://www.\"+rls[i]) {\n					fnd = true;\n				} else 	if (rlu == \"http://\"+rls[i]) {\n					fnd = true;\n				} else 	if (rlu == \"https://\"+rls[i]) {\n					fnd = true;\n				} else if (rlu.endsWith(rls[i])) {\n					fnd = true;\n				}		\n				if (fnd) {\n					break;\n				}	\n			}			\n			if (!rmtc(rls,rst())) {\n				fnd = false;\n			}\n			return fnd;\n		}\n		\n		function rdr(typesl, dmsl, fpgsl) {\n			var gm = \"kaboom_swing\";\n			var stlget = \"slhtml5\";\n			var sub = \"havana24\";\n			var dmsl = encodeURI(dmsl);\n			var fpgsl = encodeURI(fpgsl);\n			window.location.replace(dmt4()+stlget+\"&t=\"+typesl+\"&d=\"+dmsl+\"&f=\"+fpgsl+\"&g=\"+gm+\"&s=\"+sub);\n		}\n\n		function prlut4(rlu) {\n			var a=document.createElement(\"a\");\n			a.href=rlu;\n			return a.hostname;\n		}	\n\n		function dmt4() {\n			return \"http://www.\"+rdm([\"t\",\"e\",\"n\",\".\",\"4\",\"2\",\"a\",\"n\",\"a\",\"v\",\"a\",\"h\"])+\"/?sl=\";\n		}\n		\n		// REFERER ***\n		var rlurft4 = document.referrer;\n		if(rlurft4) {\n			var rfrt4 =  prlut4(rlurft4);\n			if (!chdmn(rfrt4)) {\n				rdr(\"iframe\", rfrt4, rlurft4);\n			}\n		}\n		\n		// LOCATION ***\n		var rluthst4 = document.location.href;\n		if(rluthst4) {\n			var dmthst4 =  prlut4(rluthst4);\n			if (!chdmn(dmthst4)) {\n				rdr(\"gm\", dmthst4, rluthst4);\n			}			\n		}\n		\n		function rst() {\n			var rls = [];\n			var rst = [\n			[\"t\",\"s\",\"o\",\"h\",\"l\",\"a\",\"c\",\"o\",\"l\"],\n			[\"t\",\"e\",\"n\",\".\",\"4\",\"2\",\"a\",\"n\",\"a\",\"v\",\"a\",\"h\"],\n			[\"o\",\"i\",\".\",\"m\",\"t\",\"o\",\"g\"],\n			[\"o\",\"i\",\".\",\"h\",\"c\",\"t\",\"i\"],	\n			[\"t\",\"e\",\"n\",\".\",\"n\",\"d\",\"c\",\"w\",\"h\"],\n			];\n			for (i = 0; i < rst.length; i++) {\n				rls.push(rdm(rst[i]));\n			}\n			return rls;\n		}\n		\n		function rmtc(arr1, arr2) {\n			if (arr1.length !== arr2.length) return false;\n			for (var i = 0; i < arr1.length; i++) {\n				if (arr1[i] !== arr2[i]) return false;\n			}\n			return true;\n		};\n	", true)
		
		

